### ISSUE TITLE
Unsupervised Learning, Recommenders, Reinforcement Learning/Content-Based Filtering/C3_W2_RecSysNN_Assignment.ipynb

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/StanfordMachineLearningSpecialization#3]
Show me error:

```
Cell #UNQ_C1. Can't compile the student's code. Error: NameError("name 'Model' is not defined")
 Traceback (most recent call last):
  File "/home/www/app/grading/exceptions.py", line 112, in handle_solution_errors
    yield {}
  File "/home/www/app/grading/abstract.py", line 393, in _grade
    context = compiled_code.run(cell_index=cell.index)
  File "/home/www/app/grading/submission/compiled_code.py", line 195, in run
    return list(self._code_items.values())[cell_num - 1].run()
  File "/home/www/app/grading/submission/compiled_code.py", line 54, in run
    return import_module(self.import_statement, items)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/student_solution_cells/cell_10.py", line 47, in <module>
    model = Model([input_user, input_item], output)
NameError: name 'Model' is not defined
```

![SNAG-0060](https://user-images.githubusercontent.com/428820/204804987-6d5b98e2-f17a-4851-9264-38f6dd5b896c.png)

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-49c0d5206a8d> in <module>
     34 
     35 # specify the inputs and output of the model
---> 36 model = Model([input_user, input_item], output)
     37 
     38 model.summary()

NameError: name 'Model' is not defined
```

**Comment by ERsam111** [comment]
same error with me

**Comment by johnfelipe** [comment]
Pls use this instead:
https://github.com/fatihkaratay/C3_W2_RecSysNN_Assignment/blob/main/C3_W2_RecSysNN_Assignment.ipynb
